[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5.1"
itertools = "0.13.0"
rayon = "1.10.0"
regex = "1.11.1"

[[bench]]
name = "problems"
harness = false
